import { describe, it, expect } from "vitest";
import { checkNoAdvice, checkNoAiMentions } from "@/lib/safety/no-advice";

describe("no-advice / no-prediction gate", () => {
  it("flags first-person advice", () => {
    expect(checkNoAdvice("You should appeal this decision.").ok).toBe(false);
    expect(checkNoAdvice("I recommend you lodge a review.").ok).toBe(false);
    expect(checkNoAdvice("Your best option is to apply.").ok).toBe(false);
  });

  it("flags outcome prediction", () => {
    expect(checkNoAdvice("You will win your appeal.").ok).toBe(false);
    expect(checkNoAdvice("Your claim will succeed.").ok).toBe(false);
    expect(checkNoAdvice("Success is guaranteed.").ok).toBe(false);
    expect(checkNoAdvice("You have a strong chance of winning.").ok).toBe(false);
  });

  it("allows neutral, grounded plain-language phrasing", () => {
    expect(checkNoAdvice("You may be able to ask for a review. The rules say a time limit applies.").ok).toBe(true);
    expect(checkNoAdvice("Many people in this situation ask the agency to look at it again.").ok).toBe(true);
  });
});

describe("no-AI-mentions gate", () => {
  it("flags AI / model mentions", () => {
    expect(checkNoAiMentions("This answer was generated by AI.").ok).toBe(false);
    expect(checkNoAiMentions("Powered by a large language model.").ok).toBe(false);
    expect(checkNoAiMentions("Claude wrote this.").ok).toBe(false);
  });

  it("passes ordinary product copy", () => {
    expect(checkNoAiMentions("We explain your letter in plain English.").ok).toBe(true);
  });
});
